name: Remote SSH Command
on:
  push:
    branches:
      - main
  workflow_dispatch:
      

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: update website via ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: /home/ubuntu/update_website.sh
